fresh_centrifugo:
  # Default value is 255, if you changed it in Centrifugo configuration,
  # then you can change it in bundle configuration, it effects only on validation
  channel_max_length: 255

  jwt:
    # You can set default TTL for all JWT tokens, if it not set, then default value is NULL
    # Default NULL value means that tokens will not be expired
    ttl: 86400

  api_key: '%env(CENTRIFUGO_API_KEY)%' # You can change API key here
  api_endpoint: '%env(CENTRIFUGO_API_ENDPOINT)%' # You can change API endpoint here
  secret: '%env(CENTRIFUGO_SECRET)%' # You can change secret here