nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
    
    documentation:
        info:
            title: EasyPdfApi
            description: Api for pdf service
            version: 1.0.0
        
        components:
            schemas:
                success-empty-response:
                    properties:
                        success: { type: bool }
                        data: { type: object }
    
    models: { use_jms: false }

services:
    _defaults:
        autowire: true
    
    App\Request\Nelmio\NelmioExtension: ~
    
    nelmio_api_doc.describers.components:
        class: Nelmio\ApiDocBundle\Describer\ExternalDocDescriber
        tags:
            - { name: nelmio_api_doc.describer, priority: 10 }
        arguments:
            $externalDoc: '@App\Request\Nelmio\NelmioExtension'
