services:
    nginx:
        build:
            context: docker/nginx
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-nginx
        working_dir: /var/www/app
        environment:
            - VIRTUAL_HOST=${DOMAIN}
        depends_on:
            - app
        volumes:
            ###> NGINX VOLUMES
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${CONTAINER_NAME:-unnamed}.conf
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-./}:/var/www/app
        networks:
            - reverse-proxy
            - backend
            - centrifugo

    app:
        build:
            context: docker/app
            args:
                PHP: ${PHP_VERSION}
                NAME: ${CONTAINER_NAME:-unnamed}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-app
        working_dir: /var/www/app
        stdin_open: true
        tty: true
        environment:
            ### PHP ENV ###
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
            - VIRTUAL_PROTO=fastcgi
            ###> BASH COLORS ###
            - TERM=xterm-256color
            - PS1=${PS1}
            - PHP_IDE_CONFIG=${XDEBUG_SERVER_NAME}
            - TZ=Europe/Moscow
        volumes:
            ###> BASH VOLUMES ###
            - ./docker/bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./docker/bash/.bash_history:/${USER}/.bash_history
            - ./docker/bash/.bashrc:/home/${USER}/.bashrc
            - ./docker/bash/init.sh:/init.sh
            ###> COMPOSER VOLUMES ###
            - ${COMPOSER_CONFIG_PATH:-./docker/composer/.config}:/home/${USER}/.composer
            - ${COMPOSER_CACHE_PATH:-./docker/composer/.cache}:/home/${USER}/.cache/composer
            ###> YARN VOLUMES ###
            - ${YARNRC_PATH:-./docker/yarn/.yarnrc}:/.yarnrc
            - ${YARN_CACHE_PATH:-./docker/yarn/.config}:/.cache/yarn
            - ${YARN_PATH:-./docker/yarn}:/.yarn
            ###> PHP INI VOLUME
            - ./docker/app/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-./}:/var/www/app
            ###> XDEBUG ###
            - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - backend
            - rabbitmq
            - centrifugo
            - postgres
            - minio
    
networks:
    reverse-proxy:
        name: ${PROXY_NETWORK_NAME:-docker_engine_reverse_proxy}
        external: true
    
    rabbitmq:
        name: ${RABBITMQ_NETWORK_NAME:-pdf_api_rabbitmq}
        external: true
        
    centrifugo:
        name: ${CENTRIFUGO_NETWORK_NAME:-pdf_api_centrifugo}
        external: true
        
    postgres:
        name: ${POSTGRES_NETWORK_NAME:-pdf_api_postgres}
        external: true
        
    minio:
        name: ${MINIO_NETWORK_NAME:-pdf_api_minio}
        external: true
    
    backend:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_backend_network