version: '3.9'

services:
    
    nginx:
        build:
            context: ./nginx
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-nginx
        working_dir: /var/www/app
        environment:
            - VIRTUAL_HOST=${DOMAIN}
        depends_on:
            - app
        volumes:
            ###> NGINX VOLUMES
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${CONTAINER_NAME:-unnamed}.conf
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/app
        networks:
            - reverse-proxy
            - backend
    
    app:
        build:
            context: ./app
            args:
                PHP: ${PHP_VERSION}
                NAME: ${CONTAINER_NAME:-unnamed}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-app
        working_dir: /var/www/app
        stdin_open: true
        tty: true
        environment:
            ### PHP ENV ###
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - VIRTUAL_PROTO=fastcgi
            ###> BASH COLORS ###
            - TERM=xterm-256color
            - PS1=${PS1}
            - PHP_IDE_CONFIG=${XDEBUG_SERVER_NAME}
        volumes:
            ###> BASH VOLUMES ###
            - ./bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./bash/.bash_history:/root/.bash_history
            - ./bash/.bashrc:/home/${USER}/.bashrc
            - ./bash/init.sh:/init.sh
            ###> COMPOSER VOLUMES ###
            - ${COMPOSER_CONFIG_PATH:-./composer/.config}:/home/${USER}/.composer
            - ${COMPOSER_CACHE_PATH:-./composer/.cache}:/home/${USER}/.cache/composer
            ###> YARN VOLUMES ###
            - ${YARNRC_PATH:-./yarn/.yarnrc}:/home/${USER}/.yarnrc
            - ${YARN_CACHE_PATH:-./yarn/.config}:/home/${USER}/.cache
            - ${YARN_PATH:-./yarn}:/home/${USER}/.yarn
            ###> DOCKER USER VOLUMES
            - /home/${USER}/.ssh:/home/${USER}/.ssh:rw
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PHP INI VOLUME
            - ./app/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../}:/var/www/app
            ###> XDEBUG ###
            - ./app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        networks:
            - backend
            - rabbitmq
        extra_hosts:
            - converter.pdf.local:${DOCKER_IP}
    
    postgres:
        container_name: ${CONTAINER_NAME:-unnamed}-postgres
        image: postgres:16-alpine
        restart: always
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        networks:
            - backend
            - frontend_postgres_db
    
    adminer:
        image: adminer:latest
        container_name: ${CONTAINER_NAME:-unnamed}-adminer
        restart: unless-stopped
        environment:
            ADMINER_DEFAULT_SERVER: postgres
            VIRTUAL_HOST: adminer.${DOMAIN}
        ports:
            - "8080:8080"
        networks:
            - reverse-proxy
            - frontend_postgres_db


networks:
    reverse-proxy:
        name: ${PROXY_NETWORK_NAME:-docker_engine_reverse_proxy}
        external: true
    
    rabbitmq:
        name: ${RABBITMQ_NETWORK_NAME:-pdf_frontend_rabbitmq}
        external: true
    
    backend:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_backend_network
    
    frontend_postgres_db:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_postgres_db
