version: '3.9'

services:

    nginx:
        build:
            context: ./nginx
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-nginx
        working_dir: /var/www/app
        environment:
            - VIRTUAL_HOST=${DOMAIN}
        depends_on:
            - app
        volumes:
            ###> NGINX VOLUMES
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-enabled/app.conf:/etc/nginx/sites-enabled/${CONTAINER_NAME:-unnamed}.conf
            - ./nginx/logs/access.log:/var/log/nginx/access.log
            - ./nginx/logs/error.log:/var/log/nginx/error.log
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../app}:/var/www/app
        networks:
            - frontend
            - backend

    app:
        build:
            context: ./app
            args:
                PHP: ${PHP_VERSION}
                NAME: ${CONTAINER_NAME:-unnamed}
        user: 1000:1000
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-app
        working_dir: /var/www/app
        stdin_open: true
        tty: true
        depends_on:
            - rabbitmq
        entrypoint:
            - /bin/bash
            - /init.sh
            - ${APP_ENV:-dev}
        environment:
            ### PHP ENV ###
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - VIRTUAL_PROTO=fastcgi
            ###> BASH COLORS ###
            - TERM=xterm-256color
            - PS1=${PS1}
        volumes:
            ###> BASH VOLUMES ###
            - ./bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./bash/.bash_history:/root/.bash_history
            - ./bash/.bashrc:/home/${USER}/.bashrc
            - ./bash/init.sh:/init.sh
            ###> COMPOSER VOLUMES ###
            - ${COMPOSER_CONFIG_PATH:-./composer/.config}:/home/${USER}/.composer
            - ${COMPOSER_CACHE_PATH:-./composer/.cache}:/home/${USER}/.cache/composer
            ###> YARN VOLUMES ###
            - ${YARNRC_PATH:-./yarn/.yarnrc}:/home/${USER}/.yarnrc
            - ${YARN_CACHE_PATH:-./yarn/.config}:/home/${USER}/.cache
            - ${YARN_PATH:-./yarn}:/home/${USER}/.yarn
            ###> DOCKER USER VOLUMES
            - /home/${USER}/.ssh:/home/${USER}/.ssh:rw
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PHP INI VOLUME
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
            ###> PROJECT VOLUME ###
            - ${PROJECT_PATH:-../app}:/var/www/app
        networks:
            - sql
            - backend

    rabbitmq:
        build:
            context: ./rabbitmq
        container_name: ${CONTAINER_NAME:-unnamed}-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
            interval: 5s
            timeout: 10s
            retries: 5
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - backend

    amqproxy:
        image: cloudamqp/amqproxy
        container_name: ${CONTAINER_NAME:-unnamed}-rabbitmq-proxy
        environment:
            - AMQP_URL=amqp://rabbitmq:5672
        depends_on:
            rabbitmq:
                condition: service_healthy
        networks:
            - backend

    pdf-converter-workers:
        build:
            context: ./pdf-converter-worker
            args:
                PHP: ${PHP_VERSION}
                NAME: ${CONTAINER_NAME:-unnamed}
        restart: unless-stopped
        container_name: ${CONTAINER_NAME:-unnamed}-pdf-converter-workers
        working_dir: /var/www/app
        stdin_open: true
        tty: true
        depends_on:
            rabbitmq:
                condition: service_healthy
        environment:
            ### PHP ENV ###
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
            - VIRTUAL_PROTO=fastcgi
            ###> BASH COLORS ###
            - TERM=xterm-256color
            - PS1=${PS1}
        volumes:
            ###> BASH VOLUMES ###
            - ./bash/.bash_aliases:/home/${USER}/.bash_aliases
            - ./bash/.bashrc:/home/${USER}/.bashrc
            - ./bash/init.sh:/init.sh
            ###> DOCKER USER VOLUMES
            - /home/${USER}/.ssh:/home/${USER}/.ssh:rw
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/shadow:/etc/shadow:ro
            ###> TIMEZONE VOLUMES
            - /etc/localtime:/etc/localtime:ro
            ###> PHP INI VOLUME
            - ./php/php.ini:/usr/local/etc/php/conf.d/custom.php.ini
            ###> PROJECT VOLUME ###
            - ../pdf-converter-worker:/var/www/app
            ###> SUPERVISOR VOLUMES ###
            - ./pdf-converter-worker/supervisord.conf:/etc/supervisord.conf
        ports:
            - "9001:9001"
        networks:
            - backend

networks:
    backend:
        driver: bridge
        name: ${CONTAINER_NAME:-unnamed}_backend_network

    frontend:
        name: ${PROXY_NETWORK_NAME:-docker_engine_proxy}
        external: true

    sql:
        name: ${SQL_NETWORK_NAME:-docker_engine_sql}
        external: true
