apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: api-postgres-storage-class
  resources:
    requests:
      storage: {{ .Values.volumes.data.size }}