kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-config
data:
  supervisor.conf: |
    [supervisord]
    nodaemon=true
    loglevel=info

    [program:php-fpm]
    command=php-fpm
    stdout_events_enabled=true
    stderr_events_enabled=true
    stdout_logfile=/dev/stdout
    stdout_logfile_maxbytes=0
    redirect_stderr=true

    [program:messenger-consume]
      directory=/var/www/html
      command=php bin/console messenger:consume save_processed_files --time-limit=3600
      startsecs=0
      autostart=true
      autorestart=true
      startretries=10
      stdout_events_enabled=true
      stderr_events_enabled=true
      stdout_logfile=/dev/stdout
      stdout_logfile_maxbytes=0
      redirect_stderr=true

  php.ini: |
    date.timezone = Europe/Moscow
    intl.default_locale = ru
    upload_max_filesize = 10M
    post_max_size = 100M
    memory_limit = 512M

    [opcache]
    opcache.enable = 1
    opcache.enable_cli = 1
    opcache.memory_consumption = 256
    opcache.interned_strings_buffer = 8
    opcache.max_accelerated_files = 20000
    opcache.revalidate_freq = 2
    opcache.fast_shutdown = 1
    opcache.enable_file_override = 1
    opcache.preload = /var/www/html/config/preload.php
    opcache.preload_user = www-data
    realpath_cache_size = 4096K
    realpath_cache_ttl = 600