apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    layer: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port }}
          volumeMounts:
            - name: api-config-volume
              mountPath: /etc/supervisord.conf
              subPath: supervisor.conf
            - name: api-config-volume
              mountPath: /usr/local/etc/php/conf.d/custom.php.ini
              subPath: php.ini
            - name: {{ .Chart.Name }}-jwt-keys
              mountPath: /var/www/html/config/jwt/
      volumes:
        - name: api-config-volume
          configMap:
            name: {{ .Chart.Name }}-config
        - name: {{ .Chart.Name }}-jwt-keys
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-jwt-keys-pvc
