apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-jwt-keys-pv
  labels:
    type: local
    app: {{ .Chart.Name }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.volumes.jwt_keys.data.size }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.volumes.jwt_keys.data.hostPath }}