nelmio_api_doc:
    documentation:
        components:
            schemas:
                centrifugo-anonymous-token-response:
                    properties:
                        success: { type: bool }
                        data:
                            type: object
                            properties:
                                token: string