nelmio_api_doc:
    documentation:
        components:
            schemas:
                process-upload-files-response:
                    properties:
                        success: { type: bool }
                        data:
                            type: object
                            properties:
                                uuid: string