services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    App\Request\Serializer\SerializerInterface: '@App\Request\Serializer\Strategy\Json\JsonSerializer'
    
    App\Request\Serializer\Strategy\Json\JsonSerializer: ~
    App\Request\Serializer\Strategy\Json\JsonSerializerInterface: '@App\Request\Serializer\Strategy\Json\JsonSerializer'
    
    App\Request\Serializer\Callback\UrlCallback: ~
    App\Request\Serializer\Callback\DateCallback: ~
    App\Request\Serializer\Callback\DateTimeCallback: ~
    
    App\Request\Serializer\Locator\CallbackLocator:
        arguments:
            - !service_locator
                App\Request\Serializer\Callback\UrlCallback: '@App\Request\Serializer\Callback\UrlCallback'
                App\Request\Serializer\Callback\DateCallback: '@App\Request\Serializer\Callback\DateCallback'
                App\Request\Serializer\Callback\DateTimeCallback: '@App\Request\Serializer\Callback\DateTimeCallback'
