nelmio_api_doc:
    documentation:
        components:
            schemas:
                auth-user-response:
                    properties:
                        success: { type: bool }
                        data:
                            type: object
                            properties:
                                token: string